service: lambda-sqs
frameworkVersion: "3"

useDotenv: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 900
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${self:provider.region}:811338114632:MyQueue"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${self:provider.region}:811338114632:*"

  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SOFTCENTER_API_URL: ${env:SOFTCENTER_API_URL}

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  api:
    handler: handler.handler
    memorySize: 512
    events:
      - httpApi: "*"
